[package]
name = "cve_vulnerability_analyzer"
version = "0.1.0"
edition = "2021"
authors = ["Kyle Carr"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["blocking"]  }
zip = "0.6.6"
csv = "1.3.0"
config = "0.13.4"

